import firebase_admin
from firebase_admin import auth
from firebase_admin import credentials

cred = credentials.Certificate("credentials.json")
firebase_admin.initialize_app(cred)
id_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImIwNmExMTkxNThlOGIyODIxNzE0MThhNjdkZWE4Mzc0MGI1ZWU3N2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVzdC1lZGE5NyIsImF1ZCI6InRlc3QtZWRhOTciLCJhdXRoX3RpbWUiOjE2NDgyNzI5NTksInVzZXJfaWQiOiI4dXZJT2YwbnpqUE9YSXNqT2pPRzFRQndPczczIiwic3ViIjoiOHV2SU9mMG56alBPWElzak9qT0cxUUJ3T3M3MyIsImlhdCI6MTY0ODI3Mjk1OSwiZXhwIjoxNjQ4Mjc2NTU5LCJlbWFpbCI6InRlc3RAdGVzdGNpdG8uY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAdGVzdGNpdG8uY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cN3SagJN1dGsPPpc-VoS7KjqZ2HX6ZsfNrWyUeOJjbf8qJTZjMiDkmzmd9KjSrXnToS4wv5BWjV4wIOb-k01EylcBEfQovIygIMlwAmNiIog3T8YdL_J3liA4VQsTIWSb0lFwHnhEkePmPIG6bm0CDhkQgzZmcUXQot6p_QrC6WuYeyjyLcW2NmFW7VEXogK6QPqSRNgU3KAeLAMg5J537MLUXQwDi5hVvbUX-T43XfpSTcQiK2mwglQhBHYBoKMRZjq4BRhdB3JkLUEtDS5jWM3buw7cc9ghftPAyl2uVOgWBErGZVoSr7cget9I9M7lS5Y-SYPHcC_NljOv1ZtmQ"
decoded_token = auth.verify_id_token(id_token)
print(decoded_token)
uid = decoded_token['uid']