on:
  push:
    branches: ["master"]

jobs:
  lint:
    name: Lint code using Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install Black
        run: pip install black
      - name: Check black
        id: run_black
        run: black --check ./src
      - name: Commit changes
        if: failure()
        run: |
          black ./src
          git config --global user.name 'Black Linter'
          git config --global user.email 'ignacio.pieve@gmail.com'
          git commit -m ":art: [Bot] Format Python code with Black" -a
          git push
      - name: Push changes
        if: failure()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main
      - name: Check if black was needed
        if: steps.run_black.outcome != 'success'
        run: exit 1